version: "3.8"
services:
  api:
    build: ./AppBackend
    container_name: api_c
    ports:
      - '8080:8080'
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true